# Generated by Django 4.0.3 on 2022-04-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_user_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='author',
            new_name='user_object',
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_level', models.CharField(max_length=200, null=True)),
                ('activity_points', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appone.user')),
            ],
        ),
    ]
