# Generated by Django 4.0.3 on 2022-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_rename_author_user_user_object_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='game_level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('Beginer', 'Beginer'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=200, null=True),
        ),
    ]
